name: Test the Github Action
on:
  push:
    branches: [main]
    paths-ignore:
      - test.md

jobs:
  creations_stats_job:
    name: Update profile with recent repositories and gists
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate Portfolio with Minimal style
        uses: ./
        with:
          github-username: ArsenTech
          exclusions: ArsenTech,source-codes
          target-file: test.md
          comment-tag-name: MINIMAL
          repo-list-design: minimal
          commit-message: "[AUTOMATED-CHANGE]: Updated Portfolio stats using a minimal design"

      - name: Generate Portfolio with Detailed style
        uses: ./
        with:
          github-username: ArsenTech
          exclusions: ArsenTech,source-codes
          target-file: test.md
          comment-tag-name: DETAILED
          repo-list-design: detailed
          commit-message: "[AUTOMATED-CHANGE]: Updated Portfolio stats using a detailed design"