on:
  push:
    branches:
      - main

jobs:
  creations_stats_job:
    name: A Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Main Step to test the action
        uses: ./
        with:
          github-username: ArsenTech
          exclusions: ArsenTech | source-codes
          target-file: test.md
          show-archives: true
          include-gists: false