on:
  push:
    branches:
      - main

jobs:
  creations_stats_job:
    name: A Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: test step
        uses: ArsenTech/creations-stats-workflow@v1
        with:
          - test-in: hi

      - name: Get the output time
        run: echo "The time was ${{ steps.test-out }}"