on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  creations_stats_job:
    name: A Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Main Step to test the action
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: ./
        with:
          github-username: ArsenTech
          exclusions: ArsenTech | source-codes
          target-file: test.md